services:
  # POSTGRES
  postgres:
    image: "postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greenlight
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
